import { useContext, useEffect, useState } from "react";
import { Button } from "@heroui/react";
import { ClipboardIcon, CheckIcon } from "@heroicons/react/24/outline";
import { Mint as CashuMint, Wallet as CashuWallet } from "@cashu/cashu-ts";
import { decodeEscrowLockedProofs } from "@/utils/cashu/escrow-checkout";
import {
  getOutgoingSendTokens,
  resolveOutgoingSendToken,
  OutgoingSendToken,
} from "@/utils/cashu/outgoing-send-tokens";
import {
  filterUnspentProofs,
  persistReceivedTokens,
} from "@/utils/cashu/wallet-mint-sync";
import { proofAmountToNumber } from "@/utils/cashu/proof-amount";
import {
  getLocalStorageData,
  publishProofEvent,
} from "@/utils/nostr/nostr-helper-functions";
import { copyToClipboard } from "@/utils/clipboard";
import {
  NostrContext,
  SignerContext,
} from "@/components/utility-components/nostr-context-provider";

const STATUS_LABELS: Record<OutgoingSendToken["status"], string> = {
  unclaimed: "Not yet checked",
  claimed: "Redeemed by recipient",
  reclaimed: "Reclaimed to wallet",
};

/**
 * Every cashu token generated by the wallet's Send button is durably recorded
 * (see utils/cashu/outgoing-send-tokens.ts). This section lets the user
 * re-copy a token, check whether it was redeemed, and reclaim unspent funds
 * back into the wallet — so a generated token can never be silently lost.
 */
const SentTokens = () => {
  const [entries, setEntries] = useState<OutgoingSendToken[]>([]);
  const [busyToken, setBusyToken] = useState<string | null>(null);
  const [copiedToken, setCopiedToken] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(null);

  const { signer } = useContext(SignerContext);
  const { nostr } = useContext(NostrContext);

  useEffect(() => {
    const reload = () => setEntries(getOutgoingSendTokens());
    reload();
    window.addEventListener("storage", reload);
    return () => window.removeEventListener("storage", reload);
  }, []);

  const handleCopy = async (token: string) => {
    await copyToClipboard(token);
    setCopiedToken(token);
    setTimeout(() => setCopiedToken(null), 2100);
  };

  const handleCheck = async (entry: OutgoingSendToken) => {
    setBusyToken(entry.token);
    setMessage(null);
    try {
      // Keyset-aware decode (v2 keyset IDs need the mint's keyset list) that
      // also surfaces the token's unit — receive() rejects a unit-less token
      // object. Same call shape as the escrow redeem path.
      const decoded = await decodeEscrowLockedProofs(
        entry.token,
        entry.mintUrl
      );
      const { unspent, spentCount, checked } = await filterUnspentProofs(
        decoded.mint,
        decoded.proofs
      );
      if (!checked) {
        setMessage("The mint is unreachable right now — try again shortly.");
        return;
      }
      if (unspent.length === 0) {
        resolveOutgoingSendToken(entry.token, "claimed");
        setMessage(
          "That token was already redeemed by the recipient — nothing to reclaim."
        );
        return;
      }
      const { tokens: walletTokens, history } = getLocalStorageData();
      const existingSecrets = new Set(walletTokens.map((p) => p.secret));
      const fresh = unspent.filter((p) => !existingSecrets.has(p.secret));
      if (fresh.length === 0) {
        resolveOutgoingSendToken(entry.token, "reclaimed");
        setMessage("Those funds are already back in your wallet.");
        return;
      }
      // Swap the unspent proofs at the mint for FRESH secrets before crediting
      // the wallet. This invalidates the original token, so a copy that's
      // still on someone's clipboard (or was delivered to a recipient) can no
      // longer race the user for these funds. If the swap fails, the entry
      // stays unclaimed and can be retried.
      const wallet = new CashuWallet(new CashuMint(decoded.mint));
      await wallet.loadMint();
      const reclaimedProofs = await wallet.receive({
        mint: decoded.mint,
        proofs: fresh,
        unit: decoded.unit,
      });
      const reclaimedSats = reclaimedProofs.reduce(
        (acc, p) => acc + proofAmountToNumber(p),
        0
      );
      persistReceivedTokens(reclaimedProofs, decoded.mint);
      localStorage.setItem(
        "history",
        JSON.stringify([
          {
            type: 1,
            amount: reclaimedSats,
            date: Math.floor(Date.now() / 1000),
          },
          ...history,
        ])
      );
      resolveOutgoingSendToken(entry.token, "reclaimed");
      // Best-effort nostr backup — localStorage is already the source of
      // truth for the reclaimed proofs.
      try {
        await publishProofEvent(
          nostr!,
          signer!,
          decoded.mint,
          reclaimedProofs,
          "in",
          reclaimedSats.toString()
        );
      } catch (err) {
        console.error("Failed to publish reclaimed proof backup:", err);
      }
      setMessage(
        `Reclaimed ${reclaimedSats} sats back into your wallet.${
          spentCount > 0 ? " Part of the token had already been redeemed." : ""
        }`
      );
    } catch (err) {
      console.error("Sent-token check failed:", err);
      setMessage("Couldn't check that token — try again shortly.");
    } finally {
      setBusyToken(null);
    }
  };

  if (entries.length === 0) return null;

  return (
    <div className="rounded-md border-4 border-black bg-white p-4 shadow-[8px_8px_0px_0px_rgba(0,0,0,1)]">
      <h2 className="text-lg font-bold text-black">Sent Tokens</h2>
      <p className="mb-3 text-xs text-gray-600">
        Every token you create with Send is saved here. If a token was never
        redeemed, you can copy it again or reclaim the funds back into your
        wallet.
      </p>
      <div className="flex flex-col gap-2">
        {entries.map((entry) => (
          <div
            key={entry.token}
            className="flex flex-wrap items-center justify-between gap-2 rounded-md border-2 border-black p-2"
          >
            <div className="flex flex-col">
              <span className="font-bold text-black">{entry.amount} sats</span>
              <span className="text-xs text-gray-600">
                {new Date(entry.createdAt).toLocaleString()} ·{" "}
                {STATUS_LABELS[entry.status]}
              </span>
            </div>
            <div className="flex items-center gap-2">
              {/* Never offer to copy a reclaimed token — its proofs were
                  swapped into the wallet, so the string is a live claim on
                  the user's own balance until the mint marks it spent. */}
              {entry.status !== "reclaimed" &&
                (copiedToken === entry.token ? (
                  <CheckIcon className="h-5 w-5 text-green-600" />
                ) : (
                  <ClipboardIcon
                    onClick={() => void handleCopy(entry.token)}
                    className="h-5 w-5 cursor-pointer text-black hover:text-gray-600"
                  />
                ))}
              {entry.status !== "reclaimed" && (
                <Button
                  size="sm"
                  isDisabled={busyToken !== null}
                  isLoading={busyToken === entry.token}
                  onClick={() => void handleCheck(entry)}
                  className="rounded-md border-2 border-black bg-white font-bold text-black shadow-[2px_2px_0px_0px_rgba(0,0,0,1)]"
                >
                  Check &amp; Reclaim
                </Button>
              )}
            </div>
          </div>
        ))}
      </div>
      {message ? (
        <p className="mt-3 text-center text-xs font-medium text-black">
          {message}
        </p>
      ) : null}
    </div>
  );
};

export default SentTokens;
